# Generated by Django 6.0.1 on 2026-02-03 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Website Request', 'verbose_name_plural': 'Website Requests'},
        ),
        migrations.RemoveField(
            model_name='websiterequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='websiterequest',
            name='name',
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='budget',
            field=models.CharField(blank=True, help_text='Your budget range (optional)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='business_name',
            field=models.CharField(default='Not provided', help_text='Name of the business or project', max_length=200),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='description',
            field=models.TextField(default='No description provided', help_text='Describe what you need for your website'),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='website_type',
            field=models.CharField(choices=[('ecommerce', 'E-Commerce Store'), ('blog', 'Blog/Content Site'), ('portfolio', 'Portfolio/Resume'), ('business', 'Business Website'), ('landing', 'Landing Page'), ('saas', 'SaaS Application'), ('social', 'Social Network'), ('other', 'Other')], default='other', help_text='Type of website needed', max_length=50),
        ),
        migrations.AlterField(
            model_name='websiterequest',
            name='email',
            field=models.EmailField(default='unknown@example.com', help_text='Contact email address', max_length=254),
        ),
    ]
