# Generated by Django 6.0.1 on 2026-02-03 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_websiterequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes from admin team', null=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='notified_user',
            field=models.BooleanField(default=False, help_text='Whether user was notified about status change'),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiterequest',
            name='status',
            field=models.CharField(choices=[('new', '🆕 New'), ('contacted', '📞 Contacted'), ('in_progress', '⚙️ In Progress'), ('completed', '✅ Completed')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', '🆕 New'), ('contacted', '📞 Contacted'), ('in_progress', '⚙️ In Progress'), ('completed', '✅ Completed')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', '🆕 New'), ('contacted', '📞 Contacted'), ('in_progress', '⚙️ In Progress'), ('completed', '✅ Completed')], max_length=20)),
                ('admin_message', models.TextField(blank=True, help_text='Message to send to client', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='projects.websiterequest')),
            ],
            options={
                'verbose_name': 'Status Update',
                'verbose_name_plural': 'Status Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
